server:
  port: 8701
spring:
  application:
    name: feign-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

#开启Hystrix功能
feign:
  hystrix:
    enabled: true

#配置UserService的日志级别为debug
logging:
  level:
    com.ymj.service.UserService: debug




#Feign的常用配置
#feign:
#  hystrix:
#    enabled: true #在Feign中开启Hystrix
#  compression:
#    request:
#      enabled: false #是否对请求进行GZIP压缩
#      mime-types: text/xml,application/xml,application/json #指定压缩的请求数据类型
#      min-request-size: 2048 #超过该大小的请求会被压缩
#    response:
#      enabled: false #是否对响应进行GZIP压缩
#logging:
#  level: #修改日志级别
#    com.ymj.service.UserService: debug