server:
  port: 8103
spring:
  application:
    name: eureka-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # http://${username}:${password}@${hostname}:${port}/eureka/
      defaultZone: http://ymj:123456@localhost:8005/eureka/
