
server:
  port: 8901
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        #配置存储配置信息的Git仓库
        git:
          uri: https://gitee.com/macrozheng/springcloud-config.git
          username: ymj
          password: 123456
          clone-on-start: true #开启启动时直接从git获取配置

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/